# Generated by Django 5.0.1 on 2024-01-25 03:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='create_date',
        ),
        migrations.AddField(
            model_name='text',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='text',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
